/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author nasse
 */
public class FrmResultados extends javax.swing.JFrame {

    /**
     * Creates new form FrmResultados
     */
    public FrmResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres1 = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblRecorridos = new javax.swing.JLabel();
        btnInorden = new javax.swing.JButton();
        btnPreorden = new javax.swing.JButton();
        btnPostorden = new javax.swing.JButton();
        btnNiveles = new javax.swing.JButton();
        lblPropiedades = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();
        btnAltura = new javax.swing.JButton();
        btnHojas = new javax.swing.JButton();
        btnInternos = new javax.swing.JButton();
        btnBalanceado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombres1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblNombres1.setText("RESULTADOS ÁRBOL BINARIO");

        lblNombres.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        lblNombres.setText("DOCUMENTO:");

        btnBuscar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");

        btnEliminar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");

        lblRecorridos.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        lblRecorridos.setText("RECORRIDOS:");

        btnInorden.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnInorden.setText("Inorden");

        btnPreorden.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnPreorden.setText("Preorden");

        btnPostorden.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnPostorden.setText("Postorden");

        btnNiveles.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnNiveles.setText("Niveles");

        lblPropiedades.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        lblPropiedades.setText("PROPIEDADES DEL ÁRBOL:");

        btnContar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnContar.setText("Contar");

        btnAltura.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnAltura.setText("Altura");

        btnHojas.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnHojas.setText("Hojas");

        btnInternos.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnInternos.setText("Internos");

        btnBalanceado.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnBalanceado.setText("Balanceado");

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Voto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaResultados);

        btnLimpiar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnLimpiar.setText("limpiar");

        btnCerrar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btnCerrar.setText("cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lblNombres1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblNombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPropiedades)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRecorridos)
                                .addGap(18, 18, 18)
                                .addComponent(btnInorden, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPreorden, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPostorden, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInternos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBalanceado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombres1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombres)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(btnEliminar)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecorridos)
                    .addComponent(btnInorden)
                    .addComponent(btnPreorden)
                    .addComponent(btnPostorden)
                    .addComponent(btnNiveles))
                .addGap(29, 29, 29)
                .addComponent(lblPropiedades)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContar)
                            .addComponent(btnAltura)
                            .addComponent(btnHojas)
                            .addComponent(btnInternos)
                            .addComponent(btnBalanceado))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrar)
                            .addComponent(btnLimpiar))
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAltura;
    public javax.swing.JButton btnBalanceado;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnContar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnHojas;
    public javax.swing.JButton btnInorden;
    public javax.swing.JButton btnInternos;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnNiveles;
    public javax.swing.JButton btnPostorden;
    public javax.swing.JButton btnPreorden;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblNombres;
    public javax.swing.JLabel lblNombres1;
    public javax.swing.JLabel lblPropiedades;
    public javax.swing.JLabel lblRecorridos;
    public javax.swing.JTable tablaResultados;
    public javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
